name: Checks

on:
  push:
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Run Typescript compiler
        run: yarn type-check

      - name: Run Prettier
        run: yarn format

      - name: Run Eslint
        run: yarn lint
